# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8cdfddc7e3d3ed068d97ddcef1299505c25dd8138c934cee547a21ae72f70a54080e0beeb55c4245357f6d6250a0c84a4abaa942dadeddcc2a98a0b22387cba0
  aws_bucket_name: <%= ENV["AWS_BUCKET_NAME_STAGING"] %>
  aws_region: <%= ENV["AWS_REGION_STAGING"] %>
  aws_access_key_id: <%= ENV["AWS_ACCESS_KEY_ID_STAGING"] %>
  aws_secret_access_key: <%= ENV["AWS_SECRET_ACCESS_KEY_STAGING"] %>
test:
  secret_key_base: 93d039356f6ecec46214461d44f3bb63eceb0196a6a9c8d09f9061ec3df184441ff367670dcbec520a93e6d0d613cec8d44bfaa0d226eed3b7476dc8895e76f3
  aws_bucket_name: <%= ENV["AWS_BUCKET_NAME_STAGING"] %>
  aws_region: <%= ENV["AWS_REGION_STAGING"] %>
  aws_access_key_id: <%= ENV["AWS_ACCESS_KEY_ID_STAGING"] %>
  aws_secret_access_key: <%= ENV["AWS_SECRET_ACCESS_KEY_STAGING"] %>

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  aws_bucket_name: <%= ENV["AWS_BUCKET_NAME_PRODUCTION"] %>
  aws_region: <%= ENV["AWS_REGION_PRODUCTION"] %>
  aws_access_key_id: <%= ENV["AWS_ACCESS_KEY_ID_PRODUCTION"] %>
  aws_secret_access_key: <%= ENV["AWS_SECRET_ACCESS_KEY_PRODUCTION"] %>

